<!-- Boostrap Model generated by AutoComplete🐙 -->

<!DOCTYPE html>
<html lang='fr'>

<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>Démonstration Cookies</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>

    <?php
    if ($_POST['creationCookie']) {
        $sexe = $_POST['sexe'];
        $prenom = $_POST['prenom'];
        $nom = $_POST['nom'];


        setcookie('sexe', '' . $sexe, time() + 3600 * 24, '/', '', true, true);
        setcookie('prenom', '' . $prenom, time() + 3600 * 24, '/', '', true, true);
        setcookie('nom', '' . $nom, time() + 3600 * 24, '/', '', true, true);
    }
    ?>
    <form method="POST">
        <div class="d-flex justify-content-center align-items-center flex-column" style="height: 100vh">
            <div class="text-center mb-5">
                <h1>Création d'un cookie</h1>
                <select name="sexe">
                    <option value="homme">Homme</option>
                    <option value="femme">Femme</option>
                </select>
                <input type="text" name="nom" placeholder="Insérer nom">
                <input type="text" name="prenom" placeholder="Insérer prénom">
            </div>
            <input type="submit" class="btn btn-lg btn-success" name="creationCookie" value="Créer un cookie">
        </div>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>

</html>