<!-- Boostrap Model generated by AutoComplete🐙 -->

<!DOCTYPE html>
<html lang='fr'>
<?php session_start(); ?>

<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>Démonstration session</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>
    <?php
    if (isset($_POST['creationSession'])) {
        $gender = $_POST['gender'];
        $firstname = $_POST['firstname'];
        $lastname = $_POST['lastname'];
        $birthday = $_POST['birthday'];
        $_SESSION['gender'] = $gender;
        $_SESSION['firstname'] = $firstname;
        $_SESSION['lastname'] = $lastname;
        $_SESSION['birthday'] = $birthday;
    }
    if (isset($_POST['deleteSession'])) {
        session_destroy();
    }
    ?>
    <form class="form" method="POST">

        <div class="d-flex justify-content-center align-items-center flex-column" style="height: 100vh">
            <?php if (isset($_SESSION['firstname'])) { ?>
                <div class="text-center mb-5">
                    <?= $_SESSION['gender'] . " " . $_SESSION['lastname'] = $lastname . " " . $_SESSION['firstname'] . ", née le " . $_SESSION['birthday']; ?>
                </div>
                <input type="submit" class="btn btn-lg btn-danger" name="deleteSession" value="Supprimer la session">
            <?php
            } else {
            ?>
                <div class="text-center mb-5">
                    <label>Titre de civilité</label>
                    <select name="gender">
                        <option value="Monsieur" selected>Monsieur</option>
                        <option value="Madame">Madame</option>
                        <option value="Mademoiselle">Mademoiselle</option>
                    </select><br><br>
                    <input type="text" name="firstname" placeholder="Firstname" required><br><br>
                    <input type="text" name="lastname" placeholder="Lastname" required><br><br>
                    <label>Dat ede naissance</label>
                    <input type="date" name="birthday" required>
                </div>
                <input type="submit" class="btn btn-lg btn-success" name="creationSession" value="Créer une session">
            <?php
            }
            ?>
        </div>

    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>

</html>